//! HEIC input-codec integration tests.
//!
//! Covers DE-040 acceptance criteria AC-DE-040-6..8:
//!
//! 1. Batch mode decodes HEIC and re-encodes as WebP / PNG / JPEG
//!    against the reference fixtures under `tests/fixtures/heic/`.
//!    Output bytes are byte-equivalent to the golden files under
//!    `tests/fixtures/heic/expected/` (MozJPEG / libwebp encoders
//!    are deterministic for fixed input + flag set; any byte
//!    drift here would indicate hidden non-determinism or a
//!    decode-path regression).
//! 2. Single-file stdin mode reads HEIC bytes from stdin and
//!    writes WebP bytes to stdout. Reports a structured JSON
//!    success record on stderr (matches the `--json` output
//!    shape documented in `docs/contracts/report-shape.md`).
//! 3. Failure paths surface as decode errors with the canonical
//!    failure shape: truncated HEIC, garbage HEIC, and
//!    `--output-format heic` (input-only rejection per
//!    ADR-0004 § Decision § 5).
//! 4. `heif` is accepted as an alias on `--input-format`.
//!
//! Fixtures under `tests/fixtures/heic/` were generated locally
//! via `heif-enc` (HEVC via x265; AV1 via aom) from PNG
//! gradients (operator verifies license per DE-040 § 7). The
//! sizes are smaller than the AC-DE-040-7 megapixel targets
//! (`320x480`, `480x320`, `100x100`) to keep the repo footprint
//! small; the same codec path is exercised end-to-end at every
//! size.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

fn binary() -> &'static str {
    env!("CARGO_BIN_EXE_fast-image-converter")
}

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("heic")
}

fn expected_outputs() -> PathBuf {
    fixtures().join("expected")
}

fn golden_path(name: &str) -> PathBuf {
    expected_outputs().join(name)
}

/// Three HEIC fixtures generated by `heif-enc` (HEVC x265 for
/// the first two, AV1 aom for the third). Covers both codec
/// plugin paths so libheif's libde265 / dav1d plumbing is
/// exercised end-to-end.
fn decode_inputs() -> Vec<(&'static str, &'static str)> {
    vec![
        ("portrait_hevc_3mp", "portrait_hevc_3mp.heic"),
        ("landscape_hevc_12mp", "landscape_hevc_12mp.heic"),
        ("portrait_av1_1mp", "portrait_av1_1mp.heic"),
    ]
}

fn assert_webp_magic(bytes: &[u8]) {
    assert!(
        bytes.len() >= 12,
        "WebP output too short ({} bytes)",
        bytes.len()
    );
    assert_eq!(&bytes[0..4], b"RIFF", "WebP RIFF magic missing");
    assert_eq!(&bytes[8..12], b"WEBP", "WebP magic missing");
}

fn assert_png_magic(bytes: &[u8]) {
    assert!(
        bytes.len() >= 8,
        "PNG output too short ({} bytes)",
        bytes.len()
    );
    assert_eq!(
        &bytes[0..8],
        &[0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A],
        "PNG magic missing"
    );
}

fn assert_jpeg_magic(bytes: &[u8]) {
    assert!(bytes.len() >= 3, "JPEG output too short");
    assert_eq!(bytes[0], 0xFF);
    assert_eq!(bytes[1], 0xD8);
    assert_eq!(bytes[2], 0xFF);
}

fn make_run_dir(label: &str) -> PathBuf {
    let mut p = std::env::temp_dir();
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    p.push(format!(
        "fast-image-converter-heic-{label}-{}-{}",
        std::process::id(),
        nonce
    ));
    fs::create_dir_all(&p).expect("create run dir");
    p
}

fn copy_fixture(name: &str, dst: &Path) -> PathBuf {
    let src = fixtures().join(name);
    let target = dst.join(name);
    fs::copy(&src, &target).expect("copy fixture");
    target
}

#[test]
fn heic_to_webp_round_trip_matches_golden() {
    let run = make_run_dir("webp");
    for (_, fixture_name) in decode_inputs() {
        copy_fixture(fixture_name, &run);
    }
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heic"])
        .args(["--output-format", "webp"])
        .arg("--keep-source")
        .output()
        .expect("spawn binary");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "binary failed; stderr: {stderr}"
    );

    for (golden_name, fixture_name) in decode_inputs() {
        let out_path = run.join(fixture_name.replace(".heic", ".webp"));
        let produced = fs::read(&out_path).expect("output exists");
        let golden_bytes =
            fs::read(golden_path(&format!("{golden_name}.webp"))).expect("golden exists");
        assert_eq!(
            produced, golden_bytes,
            "{fixture_name} webp output byte-mismatch"
        );
        assert_webp_magic(&produced);
    }
    let _ = fs::remove_dir_all(&run);
}

#[test]
fn heic_to_png_writes_png_magic() {
    let run = make_run_dir("png");
    copy_fixture("portrait_hevc_3mp.heic", &run);
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heic"])
        .args(["--output-format", "png"])
        .arg("--keep-source")
        .output()
        .expect("spawn binary");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "binary failed; stderr: {stderr}"
    );
    let produced = fs::read(run.join("portrait_hevc_3mp.png")).expect("output exists");
    let _ = fs::remove_dir_all(&run);
    assert_png_magic(&produced);
}

#[test]
fn heic_to_jpeg_writes_jpeg_magic() {
    let run = make_run_dir("jpg");
    copy_fixture("portrait_hevc_3mp.heic", &run);
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heic"])
        .args(["--output-format", "jpg"])
        .arg("--keep-source")
        .output()
        .expect("spawn binary");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "binary failed; stderr: {stderr}"
    );
    let produced = fs::read(run.join("portrait_hevc_3mp.jpg")).expect("output exists");
    let _ = fs::remove_dir_all(&run);
    assert_jpeg_magic(&produced);
}

#[test]
fn heic_to_heic_is_rejected_with_exit_2() {
    let run = make_run_dir("rej");
    copy_fixture("portrait_hevc_3mp.heic", &run);
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heic"])
        .args(["--output-format", "heic"])
        .output()
        .expect("spawn binary");
    let _ = fs::remove_dir_all(&run);
    assert_eq!(
        out.status.code(),
        Some(2),
        "--output-format heic must exit 2; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn jpg_to_heic_is_rejected_with_exit_2() {
    // --output-format heic is rejected regardless of the input
    // format (input-only per ADR-0004 § Decision § 5).
    let run = make_run_dir("jpgtog");
    // Copy the HEIC file but rename to .jpg so the batch
    // candidate filter still finds it; the rejection happens at
    // the dispatch layer (not the candidate filter) so the
    // --input-format jpg path is what matters.
    fs::write(run.join("dummy.jpg"), b"not really a jpg").unwrap();
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "jpg"])
        .args(["--output-format", "heic"])
        .output()
        .expect("spawn binary");
    let _ = fs::remove_dir_all(&run);
    assert_eq!(
        out.status.code(),
        Some(2),
        "--input-format jpg --output-format heic must exit 2"
    );
}

#[test]
fn heif_alias_is_accepted_as_input_format() {
    let run = make_run_dir("alias");
    copy_fixture("portrait_hevc_3mp.heic", &run);
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heif"])
        .args(["--output-format", "webp"])
        .arg("--keep-source")
        .output()
        .expect("spawn binary");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "binary failed; stderr: {stderr}"
    );
    let produced = fs::read(run.join("portrait_hevc_3mp.webp")).expect("output exists");
    let _ = fs::remove_dir_all(&run);
    assert_webp_magic(&produced);
}

#[test]
fn truncated_heic_surfaces_decode_error() {
    let run = make_run_dir("trunc");
    let truncated_target = run.join("truncated.heic");
    let src_bytes = fs::read(fixtures().join("portrait_hevc_3mp.heic")).expect("read");
    fs::write(&truncated_target, &src_bytes[..30]).expect("write truncated");
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heic"])
        .args(["--output-format", "webp"])
        .output()
        .expect("spawn binary");
    let stderr = String::from_utf8_lossy(&out.stderr);
    let _ = fs::remove_dir_all(&run);
    assert_eq!(
        out.status.code(),
        Some(1),
        "truncated HEIC must surface failure (exit 1); stderr: {stderr}"
    );
    assert!(
        stderr.contains("decode error"),
        "stderr must surface decode error; got: {stderr}"
    );
}

#[test]
fn garbage_heic_surfaces_decode_error() {
    let run = make_run_dir("garbage");
    let garbage = run.join("garbage.heic");
    let mut buf = vec![0u8; 200];
    for (i, b) in buf.iter_mut().enumerate() {
        *b = (i as u8).wrapping_mul(13);
    }
    fs::write(&garbage, &buf).expect("write garbage");
    let out = Command::new(binary())
        .arg(&run)
        .args(["--input-format", "heic"])
        .args(["--output-format", "webp"])
        .output()
        .expect("spawn binary");
    let stderr = String::from_utf8_lossy(&out.stderr);
    let _ = fs::remove_dir_all(&run);
    assert_eq!(
        out.status.code(),
        Some(1),
        "garbage HEIC must surface failure (exit 1); stderr: {stderr}"
    );
    assert!(
        stderr.contains("decode error"),
        "stderr must surface decode error; got: {stderr}"
    );
}

#[test]
fn single_file_heic_round_trip_emits_webp_magic() {
    // The single-file stdin mode reads HEIC bytes from stdin,
    // emits WebP bytes on stdout, and reports the JSON success
    // record on stderr. The decode + encode plumbing must work
    // through the in-memory path (decode_bytes / encode_to_vec)
    // without touching the filesystem.
    let src = fs::read(fixtures().join("portrait_hevc_3mp.heic")).expect("read");
    let mut child = Command::new(binary())
        .args(["--single-file"])
        .args(["--input-format", "heic"])
        .args(["--output-format", "webp"])
        .args(["--json"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn binary");
    use std::io::Write;
    let mut stdin = child.stdin.take().expect("stdin");
    stdin.write_all(&src).expect("write stdin");
    drop(stdin);
    let out = child.wait_with_output().expect("wait child");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "single-file heic->webp must exit 0; stderr: {stderr}"
    );
    assert_webp_magic(&out.stdout);
    let report: serde_json::Value =
        serde_json::from_slice(out.stderr.as_slice()).expect("JSON report parses");
    assert_eq!(report["status"], "ok");
    assert_eq!(report["mode"], "single_file");
    assert_eq!(report["input"]["format"], "heic");
    assert_eq!(report["output"]["format"], "webp");
}